# Generated by Django 4.0.6 on 2022-07-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontoturistico_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='decricao',
            new_name='descricao',
        ),
    ]
